export const ErrorCodes = {
  // Auth & Token
  INVALID_CREDENTIALS: 'ERR_INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'ERR_TOKEN_EXPIRED',
  TOKEN_REVOKED: 'ERR_TOKEN_REVOKED',
  TOKEN_INVALID: 'ERR_TOKEN_INVALID',
  TOKEN_MISSING: 'ERR_TOKEN_MISSING',
  UNAUTHORIZED: 'ERR_UNAUTHORIZED',
  FORBIDDEN: 'ERR_FORBIDDEN',

  // Validation
  VALIDATION_FAILED: 'ERR_VALIDATION_FAILED',
  VALIDATION_ERROR: 'ERR_VALIDATION_FAILED', // alias dùng nội bộ UC-13 proxy

  // User
  USER_NOT_FOUND: 'ERR_USER_NOT_FOUND',
  EMAIL_ALREADY_EXISTS: 'ERR_EMAIL_ALREADY_EXISTS',
  EMAIL_NOT_VERIFIED: 'ERR_EMAIL_NOT_VERIFIED',
  OTP_INVALID: 'ERR_OTP_INVALID',

  // System
  INTERNAL_ERROR: 'ERR_INTERNAL_ERROR',
  ROUTE_NOT_FOUND: 'ERR_ROUTE_NOT_FOUND',

  // Voice AI (UC-13)
  MODEL_NOT_FOUND: 'ERR_MODEL_NOT_FOUND',
  MODEL_UNAVAILABLE: 'ERR_MODEL_UNAVAILABLE',
  DOWNLOAD_RATE_LIMITED: 'ERR_DOWNLOAD_RATE_LIMITED',
} as const;
